image: docker:latest

stages:
  - build
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t alprapp-image .

test:
  stage: test
  script:
    - docker run alprapp-image npm test